### PR TITLE
fix : 2021 轉換靜態頁

### LINKED ISSUE #338: 2021 轉換靜態頁

### PR DESCRIPTION
**Pull request by baby230211**
## Types of changes

build(nuxt-generate): add dynamic routes configuration and update to use asyncData fetching data

## Steps to Test This Pull Request

1. npm run json-server
2. npm run generate
3. npm run start
4. Check out if all pages works well.

## Expected behavior

All pages should show up data as usual.
## Related Issue

fix #338

### CODE REVIEW

File: pages/conference/_eventType/index.vue [hunk 1]
```diff
@@ -76,16 +76,26 @@ export default {
...
-    asyncData({ redirect, params }) {
+    async asyncData({ redirect, store, params, payload }) {
         const eventType = params.eventType
         if (!['talks', 'tutorials'].includes(eventType)) {
             redirect('/')
         }
+        if (payload && Object.keys(payload).length !== 0)
+            return { eventType, speechesData: payload }
+
+        await store.dispatch('$getSpeechesData', eventType)
```
Comment (yungshenglu) [inline pages/conference/_eventType/index.vue:87]: 有需要加 try-catch?

File: pages/conference/keynotes.vue [hunk 2]
```diff
@@ -127,23 +127,23 @@ export default {
         ExtLink,
         Youtube,
     },
-    data() {
+    async asyncData({ store, app, payload }) {
+        if (payload) return { keynotesData: payload }
+        await store.dispatch('$getKeynotesData')
+        const keynotesData = store.state.keynotesData.map((keynote) => ({
```
Comment (yungshenglu) [inline pages/conference/keynotes.vue:133]: `keynotesData?.map`

File: pages/conference/_eventType/index.vue [hunk 3]
```diff
@@ -76,16 +76,26 @@ export default {
...
+        const speechesData = store.state.speechesData.map((speech) => ({
```
Comment (yungshenglu) [inline pages/conference/_eventType/index.vue:88]: `speechesData?.map`

File: pages/events/jobs-gather.vue [hunk 4]
```diff
@@ -45,19 +45,22 @@ export default {
         JobsCardCollection,
         JobsPanel,
     },
+    async asyncData({ store, app, payload }) {
+        if (payload) return { jobsData: payload }
+        await store.dispatch('$getJobsData')
+        const jobsData = store.state.jobsData.map((sponsor) => ({
```
Comment (yungshenglu) [inline pages/events/jobs-gather.vue:51]: `jobsData?.map`

**Review by yungshenglu — APPROVED** [review]
👍🏼
