### PR TITLE
fix: leafleat module import error in ssr mode

### LINKED ISSUE #471: [Bug Report] development environment setup failure in local
## Description

**Describe the bug**
1.  docker compose environment run failed in local
2. "window is not defined" was displayed

## Steps to Reproduce

1. Follow [Steps in Readme](https://github.com/pycontw/pycontw-frontend/blob/main/README.md) set up development environment on local.
2. Go to http://localhost:3000/2024/ and check if 2024 landing page shown

## Expected Behavior
development environment built successfully with 2024 page landed as [2024 Website](https://tw.pycon.org/2024/en-us)

### PR DESCRIPTION
**Pull request by rockleona**
## Types of changes

* **Bugfix**

## Description

1. Install `nuxt-leaflet`
2. Remove `plugins/leaflet.js` in `nuxt.config.js`
3. Remove every imported `vue2-leaflet` components in `components/venue/VenueMap.vue`
4. Remove icon related import 
5. Confirmed **Step 4** is the problem that cause `window is not defined` error

## Steps to Test This Pull Request

using **node v16.x**

1. `npm install --legacy-peer-deps` 
2. `npm run dev`
3. Go to browser and enter url `http://localhost:3000/2024/zh-hant/venue`

## Related Issue
resolve #471

### CODE REVIEW

**Comment by SivanYeh** [comment]
It worked in "http://localhost:3000/2024/zh-hant/venue" on my laptop(with node v16.20.2):
image

However it didn't work on landing page:
image

Maybe 2024 landing image wasn't updated? Have you tried git rebase with main branch?

**Comment by rockleona** [comment]
> Maybe 2024 landing image wasn't updated? Have you tried git rebase with main branch?

May I ask which commit had updated the image? I'll check later to fix this.
But if 2024 landing image works well in the lastest commit, and do not have any conlict, I think it will be fine.

**Comment by SivanYeh** [comment]
> > Maybe 2024 landing image wasn't updated? Have you tried git rebase with main branch?
> 
> May I ask which commit had updated the image? I'll check later to fix this. But if 2024 landing image works well in the lastest commit, and do not have any conlict, I think it will be fine.

Here you are! Check these two: 
https://github.com/pycontw/pycontw-frontend/commit/3a35ccfb848c1716759197c7905469c743ae91be#diff-ada816b2089b0b540842867ceef1ed01f10b16f72f963dbb98cc43eaa914ec8d

https://github.com/pycontw/pycontw-frontend/commit/c63b93c6b08184f0d96300ca4f0748c8cb390bda

**Comment by rockleona** [comment]
> > > Maybe 2024 landing image wasn't updated? Have you tried git rebase with main branch?
> > 
> > 
> > May I ask which commit had updated the image? I'll check later to fix this. But if 2024 landing image works well in the lastest commit, and do not have any conlict, I think it will be fine.
> 
> Here you are! Check these two: [3a35ccf](https://github.com/pycontw/pycontw-frontend/commit/3a35ccfb848c1716759197c7905469c743ae91be)
> 
> [c63b93c](https://github.com/pycontw/pycontw-frontend/commit/c63b93c6b08184f0d96300ca4f0748c8cb390bda) cc @mattwang44

hmm....I've check that these commits are in this PR as well, that's werid,
I'll me check it later and update with you.

**Comment by rockleona** [comment]
> The index page and venue page work fine on my side.
> 
> ```
> rm -rf node_modules dist
> nvm use lts/fermium  # v14.21.3
> npm i
> npm run dev
> 
> # run `npm run json-server` from another terminal
> ```
> 
> However, I got these messages from the terminal. Could be existing issues.
> 
> image

Hi @SivanYeh, I've rebase the code and  follow the steps that Matt tested,
it works fine to me, would you give it a try?

File: pages/index.vue [hunk 1]
```diff
@@ -163,7 +163,7 @@ export default {
     },
     fetchOnServer: false,
     computed: {
-        ...mapState(['sponsorsData']),
+        // ...mapState(['sponsorsData']),
```
Comment (rockleona) [inline pages/index.vue:166]: Hi @mattwang44, I've comment out this line and  L121, whiche can fix the error.

That error you'd mentioned is based on the setup for archive, 
I think it will works the same when we use `asyncData` in the file

File: components/venue/VenueMap.vue [hunk 2]
```diff
@@ -97,24 +77,31 @@ export default {
...
+            this.L = await import('leaflet')
+            this.icon = this.L.icon({
+                iconUrl: '/snake.png',
+                shadowUrl: '/snake-bg.png',
+                iconSize: [42, 42],
+                iconAnchor: [21, 21],
+                shadowSize: [45, 55],
+                shadowAnchor: [25, 30],
+            })
+        },
```
Comment (rockleona) [inline components/venue/VenueMap.vue:104]: Thanks to @baby230211 suggestion, the code works well.

**Comment by SivanYeh** [comment]
It worked perfectly here too! You nailed it Leon. I opened two terminals and followed the steps outlined below:
Terminal1:
```
nvm use v16
npm run json-server
```

Terminal2:
```
nvm use v16
npm install —legacy-peer-deps
npm run dev
Go to browser and enter url http://localhost:3000/2024/zh-hant/venue
```

Interesting stuff, not vital at the moment but we may have to keep in mind: 
Wen I tried to reproduce Matt’s instructions, I got error caused by v14:
```
ERROR: npm v10.4.0 is known not to run on Node.js v14.21.3.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.

ERROR:
/Users/cat/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/@npmcli/agent/lib/agents.js:105
    options.lookup ??= this.#options.lookup
                   ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/cat/.nvm/versions/node/v14.21.3/lib/node_modules/npm/node_modules/@npmcli/agent/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
````
These errors can be solved by using node v16.

**Review by SivanYeh — APPROVED** [review]
LGTM

**Comment by baby230211** [comment]
Thanks @rockleona 
This looks great, could you also help remove unused leaflet code?
- plugins/leaflet.js
- Nuxt.config.js

**Comment by rockleona** [comment]
@baby230211 , I just removed them,  have a look if youre free.

**Review by baby230211 — APPROVED** [review]
LGTM

**Comment by tyuchx** [comment]
LGTM
